environments:
  dev:
    values:
      - environments/dev.yaml
      - values/dev.yaml
  prod:
    values:
      - environments/prod.yaml
      - values/prod.yaml

---
releases:
  - name: flask-app
    namespace: default
    chart: ./flask-eks
    version: 0.1.0
