name: Deploy Flask to EKS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY

      - name: Build & Push Docker image
        run: |
          cd app
          docker buildx create --use || true
          docker buildx build --platform linux/amd64 -t flask-eks-app --load .
          docker tag flask-eks-app:latest $ECR_REPOSITORY:latest
          docker push $ECR_REPOSITORY:latest

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.29.0

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name flask-eks-eks

      - name: Install helm & helmfile
        run: |
          # Install helm
          curl -sSL -o helm.tar.gz https://get.helm.sh/helm-v3.14.0-linux-amd64.tar.gz
          tar -zxvf helm.tar.gz
          sudo mv linux-amd64/helm /usr/local/bin/helm

          # Install helmfile (specific version)
          curl -sSL -o helmfile https://github.com/helmfile/helmfile/releases/download/v0.155.0/helmfile_0.155.0_linux_amd64
          chmod +x helmfile
          sudo mv helmfile /usr/local/bin/helmfile

          # Optional: install helm-diff plugin
          helm plugin install https://github.com/databus23/helm-diff || true

      - name: Deploy to EKS using Helmfile
        run: |
          cd helm
          helmfile apply