name: Deploy Flask to EKS

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      CLUSTER_NAME: flask-eks-eks

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Determine environment
        id: env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "env=prod" >> "$GITHUB_OUTPUT"
          else
            echo "env=dev" >> "$GITHUB_OUTPUT"
          fi

      - name: Debug env
        run: echo "🌍 Deploying to ${{ steps.env.outputs.env }}"

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY

      - name: Build & Push Docker image
        run: |
          docker buildx create --use || true
          docker buildx build --platform linux/amd64 -t flask-eks-app --load ./app
          docker tag flask-eks-app:latest $ECR_REPOSITORY:latest
          docker push $ECR_REPOSITORY:latest

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.29.0

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

      - name: Install helm & helmfile
        run: |
          curl -LO https://get.helm.sh/helm-v3.14.0-linux-amd64.tar.gz
          tar -zxvf helm-v3.14.0-linux-amd64.tar.gz
          sudo mv linux-amd64/helm /usr/local/bin/helm

          curl -L -o helmfile https://github.com/helmfile/helmfile/releases/download/v1.0.0/helmfile_1.0.0_linux_amd64.tar.gz
          tar -xvzf helmfile_1.0.0_linux_amd64.tar.gz
          sudo mv helmfile /usr/local/bin/helmfile

          helm plugin install https://github.com/databus23/helm-diff || true

      - name: Deploy with Helmfile
        run: |
          cd helm
          helmfile -e ${{ steps.env.outputs.env }} apply